// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD02BcxfBojZYZHY04QMT6n2-GqR60GxGc',
    appId: '1:248930313822:web:a3f39f414c65d04753b6cf',
    messagingSenderId: '248930313822',
    projectId: 'flutter-firebase-firesto-7158e',
    authDomain: 'flutter-firebase-firesto-7158e.firebaseapp.com',
    storageBucket: 'flutter-firebase-firesto-7158e.firebasestorage.app',
    measurementId: 'G-LC6KP4399X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBydf5mpttiNXjnAbmia3dqU5WQIwYWLnA',
    appId: '1:248930313822:android:ad98c804bdd0b98653b6cf',
    messagingSenderId: '248930313822',
    projectId: 'flutter-firebase-firesto-7158e',
    storageBucket: 'flutter-firebase-firesto-7158e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcbve3eBygm5zZxnIw1-fNq1Uut3OhrRE',
    appId: '1:248930313822:ios:c6c271cd568ab9a053b6cf',
    messagingSenderId: '248930313822',
    projectId: 'flutter-firebase-firesto-7158e',
    storageBucket: 'flutter-firebase-firesto-7158e.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcbve3eBygm5zZxnIw1-fNq1Uut3OhrRE',
    appId: '1:248930313822:ios:c6c271cd568ab9a053b6cf',
    messagingSenderId: '248930313822',
    projectId: 'flutter-firebase-firesto-7158e',
    storageBucket: 'flutter-firebase-firesto-7158e.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD02BcxfBojZYZHY04QMT6n2-GqR60GxGc',
    appId: '1:248930313822:web:7d23c27f126a746153b6cf',
    messagingSenderId: '248930313822',
    projectId: 'flutter-firebase-firesto-7158e',
    authDomain: 'flutter-firebase-firesto-7158e.firebaseapp.com',
    storageBucket: 'flutter-firebase-firesto-7158e.firebasestorage.app',
    measurementId: 'G-XD8SLSNSMJ',
  );
}
